language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2


install:
  - ./install-dependencies.sh

script:
  - vendor/bin/phpunit

#after_script:
#  - wget https://scrutinizer-ci.com/ocular.phar
#  - php ocular.phar code-coverage:upload --format=php-clover coverage.xml
